### ISSUE TITLE
Mapping problem

### ISSUE THREAD

**Issue by johanneskoch94** [pik-piam/mrland#10]
Hi Marcos,
unfortunately I'm also getting an error here:
https://github.com/pik-piam/mrland/blob/6b1e811370d0482e6ce2046e68a5e8c89766ee9f/R/calcPastureYield.R#L37
which breaks:
https://github.com/pik-piam/mrland/blob/6b1e811370d0482e6ce2046e68a5e8c89766ee9f/R/fullMAGPIE.R#L90
does this run on your side?

**Comment by mppalves** [comment]
Hi Johannes, I just fixed the bugs. As far as I tested, they are working for me. If you still have problems, please contact me on mattermost! thanks
