### ISSUE TITLE
Incompatible mappings

### ISSUE THREAD

**Issue by johanneskoch94** [pik-piam/mrland#8]
Hey Marcos, this line is throwing an error on my side, how about on yours?
https://github.com/pik-piam/mrland/blob/ec569b658469ab87a1b400f3ac92a7725bcb8137/R/fullMAGPIE.R#L89
thanks!

**Comment by johanneskoch94** [comment]
As far as I can tell, the error is thrown in the aggregation part of the madrat::calcOutput. Setting `aggregate = FALSE` doesn't produce a warning.

**Comment by mppalves** [comment]
Ok, thank! I think I know how to fix it.

I have a meeting starting in a few minutes, and I wont be able to fix it now. Can you comment that line out from the fullMAGPIE function for now?
thanks

**Comment by johanneskoch94** [comment]
Ok! Super, I'll do that.
